[package]
name = "libncurses"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://invisible-mirror.net/archives/ncurses/current/"

[[package.metadata.build-package.external-files]]
url = "https://invisible-mirror.net/archives/ncurses/current/ncurses-6.4-20231209.tgz"
sha512 = "293b91b20f676230e28dadfc6ec811ac898e56d558d919566bf515d91ee9bd5df222f56da593d5ce249550a38ad4a9d206df2761f170c7738c9e8a3ea564e42a"

[build-dependencies]
glibc = { path = "../glibc" }
