[package]
name = "ethtool"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://kernel.org/pub/software/network/ethtool/"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-6.6.tar.xz"
sha512 = "1e7eae3abe59e6af4bce0ebedd0a7ea84d1b0adc7693a0f03021c4096677096a022fdae521ac02413f9db46ee232b89dd2015a116845aa6ca7686fdda50a5b21"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
