schema-version = 1
release-version = "1.19.3"

[sdk]
registry = "234037160054.dkr.ecr.us-east-1.amazonaws.com"
name = "bottlerocket-sdk"
version = "v0.37.0"

[toolchain]
registry = "234037160054.dkr.ecr.us-east-1.amazonaws.com"
name = "bottlerocket-toolchain"
version = "v0.37.0"
