[package]
name = "dbus-broker"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/bus1/dbus-broker/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bus1/dbus-broker/releases/download/v35/dbus-broker-35.tar.xz"
sha512 = "409e415889bd53b78e92ba077455e5583852a071e233e4b23dcbb23d8a367f177d6c8138e6fc113dcfe48440b68d594c1a076cb43ef445d472645f671d5ae033"

[build-dependencies]
glibc = { path = "../glibc" }
libexpat = { path = "../libexpat" }
libselinux = { path = "../libselinux" }
systemd = { path = "../systemd" }
