[package]
name = "procps"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://gitlab.com/procps-ng/procps/-/tags"

[[package.metadata.build-package.external-files]]
url = "https://gitlab.com/procps-ng/procps/-/archive/v4.0.4/procps-v4.0.4.tar.gz"
sha512 = "b7ba28391b71ad95fda6de25c539132face53c308402d615aa6f5bdde0b5c3de3f5b1b7623e4b1fb92dc36bc2d5b73268afda21c992ef94b1059ba0cd2b6a340"

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
