[package]
name = "liblzma"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://tukaani.org/xz"

[[package.metadata.build-package.external-files]]
url = "https://tukaani.org/xz/xz-5.4.5.tar.xz"
sha512 = "5cbc3b5bb35a9f5773ad657788fe77013471e3b621c5a8149deb7389d48535926e5bed103456fcfe5ecb044b236b1055b03938a6cc877cfc749372b899fc79e5"

[build-dependencies]
glibc = { path = "../glibc" }
