[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# ECS agent
[package.metadata.build-package]
releases-url = "https://github.com/aws/amazon-ecs-agent/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.79.2/amazon-ecs-agent-1.79.2.tar.gz"
sha512 = "28abd355f3a1fb2170b6d2b3064d2f6057e0d8f6d7a37df77cfe91e45ee50ab00cb5ca3ea64fdca82bca29fcdb19c4cd966db0173473cea68612b416c23dae77"

# The ECS agent repository includes two CNI plugins as git submodules.  git
# archive does not include submodules, so the tarball above does not include
# the source of those plugins.  Instead, we include the CNI plugin source
# directly.
# You can get the commit SHA for the submodules for a particular ecs-agent release here:
# https://github.com/aws/amazon-ecs-agent/blob/ECS_AGENT_VERSION/agent/ecscni/plugin_test.go#L29-L34
[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-cni-plugins/archive/53a8481891251e66e35847554d52a13fc7c4fd03/amazon-ecs-cni-plugins.tar.gz"
sha512 = "e819c1aae509d19461999bf717d126b3e918b73dc6049e415c4911be6cb11159404bb45bb6c92cdfa16b5b30bb174731e972e3f2be44fa0b51bbc7a969049ab7"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-vpc-cni-plugins/archive/be5214353252f8315a1341f4df9ffbd8cf69000c/amazon-vpc-cni-plugins.tar.gz"
sha512 = "b1aa61d0000ff732dae67213cea2eac49363c048416716e27f36b2b43f6227db8b15ead27c43c5fd623569a49572cb6b2149c86d69363f75cec4620ddc9ef47b"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# `docker-engine` is only needed at runtime, and is included in the variant
# definition.
# docker-engine = { path = "../docker-engine" }
# `iptables` is only needed at runtime, and is pulled in by `release`.
# iptables = { path = "../iptables" }
amazon-ssm-agent = { path = "../amazon-ssm-agent" }
