[package]
name = "libinih"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/benhoyt/inih/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/benhoyt/inih/archive/refs/tags/r58.tar.gz"
path = "inih-r58.tar.gz"
sha512 = "d69f488299c1896e87ddd3dd20cd9db5848da7afa4c6159b8a99ba9a5d33f35cadfdb9f65d6f2fe31decdbadb8b43bf610ff2699df475e1f9ff045e343ac26ae"

[build-dependencies]
glibc = { path = "../glibc" }
