[package]
name = "nvidia-k8s-device-plugin"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/k8s-device-plugin/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/k8s-device-plugin/archive/v0.14.3/v0.14.3.tar.gz"
path = "k8s-device-plugin-0.14.3.tar.gz"
sha512 = "cd60ca6b87df8d0a4a34a95284253a7129b6fb617e6df639a92c312919f36343584472f148fac95c47c54dbbb883b2e1c8e564c6921c2a6b3e49819fb27f1f85"

[build-dependencies]
glibc = { path = "../glibc" }
