[clarify."github.com/sean-/seed"]
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xd5734f17 },
]

[clarify."github.com/miekg/dns"]
expression = "BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0xe41dd36c },
    { path = "LICENSE", hash = 0xfc8f12ff }
]

[clarify."sigs.k8s.io/yaml"]
expression = "MIT AND BSD-3-Clause AND Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xcdf3ae00 },
]
