[package]
name = "docker-cli"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v25.0.2/cli-25.0.2.tar.gz"
sha512 = "66c6c408f4f5f42ded007948a69fb66cf0d1f0462a1700fb4efaaf70755285e7179d5bd61e7963f77a088e5f27a8a42b0501be1331948d0ff30bd829b205b5ad"

[build-dependencies]
glibc = { path = "../glibc" }
