[package]
name = "libnl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/thom311/libnl/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/thom311/libnl/archive/libnl3_9_0.tar.gz"
sha512 = "7182752ccd3663f14fc7bce20d134c42e54b8305b67e44e509027aab0150a5ef056f373332d22f87386a827f8ca8b7bdaf2bd5d410982210d28ec071f31ccc73"

[build-dependencies]
glibc = { path = "../glibc" }
