[package]
name = "iputils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/iputils/iputils/releases"

[[package.metadata.build-package.external-files]]
path = "iputils-20231222.tar.gz"
url = "https://github.com/iputils/iputils/archive/20231222.tar.gz"
sha512 = "499cf870210d4aec28dc8c2305892d57d3c1aee0ddbdf0ecb5a4887cd41995bf9e07ca8eabb1e3a38f56d408ea6b54ea9c436e76098f58d530752b862b2598ff"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
