[package]
name = "iputils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/iputils/iputils/releases"

[[package.metadata.build-package.external-files]]
path = "iputils-20240117.tar.gz"
url = "https://github.com/iputils/iputils/archive/20240117.tar.gz"
sha512 = "1755de6adb509418507c3f10521715ff3bf7ba38d3bbd9a102a48ae0a9f88fcb1f457bcb38624dce2281912e0e0ffc3fbf74e0e618ed2d21014710e967c7dad3"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
