[package]
name = "nvidia-fabrics-manager"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://developer.download.nvidia.com/compute/cuda/redist/fabricmanager"

[[package.metadata.build-package.external-files]]
url = "https://developer.download.nvidia.com/compute/cuda/redist/fabricmanager/linux-x86_64/fabricmanager-linux-x86_64-545.23.08-archive.tar.xz"
sha512 = "974570b27bcb75e448c332fb1ab9f8c905df7ef0c6acee4caa5665ae25a0d7f33296fd78c1adc5f50bf556fd31cba3ab59254ad311055ea632234bda6dea3a65"

[build-dependencies]
glibc = { path = "../glibc" }
