[package]
name = "chrony"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://download.tuxfamily.org/chrony"

[[package.metadata.build-package.external-files]]
url = "https://download.tuxfamily.org/chrony/chrony-4.5.tar.gz"
sha512 = "58a449e23186da799064b16ab16f799c1673296984b152b43e87c620d86e272c55365e83439d410fc89e4e0ba0befd7d5c625eac78a6665813b7ea75444f71b5"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libncurses = { path = "../libncurses" }
readline = { path = "../readline" }
