[package]
name = "bork"
version = "0.1.0"
authors = ["Samuel Mendoza-Jonas <samjonas@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
serde_json = "1"

# generation logic moved to updates settings extension
settings-extension-updates = { path = "../../settings-extensions/updates", version = "0.1" }
