[package]
name = "libattr"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://download-mirror.savannah.gnu.org/releases/attr"

[[package.metadata.build-package.external-files]]
url = "https://download-mirror.savannah.gnu.org/releases/attr/attr-2.5.2.tar.xz"
sha512 = "f587ea544effb7cfed63b3027bf14baba2c2dbe3a9b6c0c45fc559f7e8cb477b3e9a4a826eae30f929409468c50d11f3e7dc6d2500f41e1af8662a7e96a30ef3"

[build-dependencies]
glibc = { path = "../glibc" }
