[package]
name = "containerd"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containerd/containerd/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.6.26/containerd-1.6.26.tar.gz"
sha512 = "a642ef48f858aaf7f7830ab2ad23d4fc5102dc939d9f8e017ea86772199fe4bd9c7eb550a640b0b9e8b6963d88a1aca87d09eb02e109fc8341f39cfeda47860b"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
runc = { path = "../runc" }
pigz = { path = "../pigz" }
