[package]
name = "util-linux"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.kernel.org/pub/linux/utils/util-linux"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-2.39.3.tar.xz"
sha512 = "a2de1672f06ca5d2d431db1265a8499808770c3781019ec4a3a40170df4685826d8e3ca120841dcc5df4681ca8c935a993317bd0dc70465b21bf8e0efef65afa"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
libncurses = { path = "../libncurses" }
