[package]
name = "cni-plugins"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/containernetworking/plugins/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containernetworking/plugins/archive/v1.4.0/plugins-1.4.0.tar.gz"
sha512 = "d812663fb58cfa2bfe35dd70940586d47f11feddd35a86ea7639197b022f9c0e0f487679e2e968eebf1f80b8b1d9cfbd0fe99d80590ae60a8128fa393d713e0b"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# `iptables` is only needed at runtime, and is pulled in by `release`.
# iptables = { path = "../iptables" }
