[package]
name = "libacl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://download-mirror.savannah.gnu.org/releases/acl"

[[package.metadata.build-package.external-files]]
url = "https://download-mirror.savannah.gnu.org/releases/acl/acl-2.3.2.tar.gz"
sha512 = "31aeb39958d8af5d08933dd3a89333a41025c3eb49fc461fa3c291caca51dad575ec13faeb7deba9b3c2ebf7615be7d45e2b78e50d4f83d8ec933c95931a7682"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
